import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'

export function generateToken(): string {
  return crypto.randomBytes(32).toString('hex')
}

export function generateWebhookSecret(): string {
  return crypto.randomBytes(24).toString('hex')
}

export function findRepoRoot(startDir: string = process.cwd()): string | null {
  let dir = startDir
  while (true) {
    if (fs.existsSync(path.join(dir, '.env.example'))) {
      return dir
    }
    const parent = path.dirname(dir)
    if (parent === dir) return null
    dir = parent
  }
}

export interface EnvConfig {
  supabaseUrl: string
  supabaseServiceRoleKey: string
  engineToken: string
  schedulerEnabled: boolean
  discordMode: 'webhook' | 'bot' | 'skip'
  discordWebhookUrl?: string
  discordBotToken?: string
  discordChannelId?: string
  discordApproverIds?: string
  vercelEnabled: boolean
  vercelWebhookSecret?: string
  vercelProjectMap?: string
}

export function buildEnvContent(config: EnvConfig): string {
  const lines: string[] = [
    '# Generated by bionic init',
    '',
    '# Supabase',
    `SUPABASE_URL=${config.supabaseUrl}`,
    `SUPABASE_SERVICE_ROLE_KEY=${config.supabaseServiceRoleKey}`,
    '',
    '# Engine',
    `BIONIC_ENGINE_TOKEN=${config.engineToken}`,
    `BIONIC_ENGINE_HOST=127.0.0.1`,
    `PORT=3001`,
    `BIONIC_PROJECT_ID=project_bionic`,
    `NEXT_PUBLIC_ENGINE_URL=http://localhost:3001`,
    '',
    '# Scheduler',
    `BIONIC_SCHEDULER_ENABLED=${config.schedulerEnabled}`,
    `BIONIC_DIGEST_CRON=0 9 * * 1`,
    `BIONIC_DIGEST_TIMEZONE=Asia/Tokyo`,
    '',
    '# Discord',
  ]

  if (config.discordMode === 'webhook' && config.discordWebhookUrl) {
    lines.push(`DISCORD_WEBHOOK_URL=${config.discordWebhookUrl}`)
    lines.push(`# BIONIC_DISCORD_BOT_TOKEN=`)
    lines.push(`# BIONIC_DISCORD_CHANNEL_ID=`)
    lines.push(`# BIONIC_DISCORD_APPROVER_IDS=`)
  } else if (config.discordMode === 'bot') {
    lines.push(`# DISCORD_WEBHOOK_URL=`)
    lines.push(`BIONIC_DISCORD_BOT_TOKEN=${config.discordBotToken ?? ''}`)
    lines.push(`BIONIC_DISCORD_CHANNEL_ID=${config.discordChannelId ?? ''}`)
    lines.push(`BIONIC_DISCORD_APPROVER_IDS=${config.discordApproverIds ?? ''}`)
  } else {
    lines.push(`# DISCORD_WEBHOOK_URL=`)
    lines.push(`# BIONIC_DISCORD_BOT_TOKEN=`)
    lines.push(`# BIONIC_DISCORD_CHANNEL_ID=`)
    lines.push(`# BIONIC_DISCORD_APPROVER_IDS=`)
  }

  lines.push('')
  lines.push('# Quiet Hours')
  lines.push(`BIONIC_QUIET_HOURS_START=23`)
  lines.push(`BIONIC_QUIET_HOURS_END=7`)
  lines.push(`BIONIC_QUIET_HOURS_TIMEZONE=Asia/Tokyo`)

  if (config.vercelEnabled) {
    lines.push('')
    lines.push('# Vercel')
    lines.push(`VERCEL_WEBHOOK_SECRET=${config.vercelWebhookSecret ?? ''}`)
    lines.push(`BIONIC_VERCEL_PROJECT_MAP=${config.vercelProjectMap ?? ''}`)
  } else {
    lines.push('')
    lines.push('# Vercel (not configured)')
    lines.push(`# VERCEL_WEBHOOK_SECRET=`)
    lines.push(`# BIONIC_VERCEL_PROJECT_MAP=`)
  }

  lines.push('')
  return lines.join('\n')
}

export function writeEnvFile(repoRoot: string, content: string): void {
  const envPath = path.join(repoRoot, '.env.local')
  fs.writeFileSync(envPath, content, 'utf-8')
}

export function envFileExists(repoRoot: string): boolean {
  return fs.existsSync(path.join(repoRoot, '.env.local'))
}
